version: 0.2
phases:
  install:
    runtime-versions:
        golang: 1.x
  build:
    commands:
      - GOOS=linux go build main.go && zip archive.zip main
      - export ARTIFACTS_BUCKET=mybucketabc235d
      - aws s3 cp archive.zip s3://$ARTIFACTS_BUCKET/$FunctionName/archive.zip
      - aws lambda update-function-code --function-name $FunctionName --s3-bucket $ARTIFACTS_BUCKET --s3-key archive.zip

