
version: 0.2
phases:
  install:
    runtime-versions:
        golang: 1.x
  build:
    commands:
      - GOOS=linux go build main.go && zip archive.zip main
      - export ARTIFACTS_BUCKET=mybucketabc235d
      - aws s3 cp archive.zip s3://$ARTIFACTS_BUCKET/archive.zip
artifacts:
  type: zip
  files: 
    - lambda.yaml
    - archive.zip
    - prodParameter.json
    - qaParameter.json
    - devParameter.json
