
version: 0.2
phases:
  install:
    runtime-versions:
        golang: 1.x
  build:
    commands:
      - GOOS=linux go build main.go && zip archive.zip main
      
artifacts:
  type: zip
  paths:
    - '*'
