AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: main
      FunctionName: PipelineLambdaFunction
      Code:
        S3Bucket: mybucketabc235d
        S3Key: archive.zip
      Runtime: go1.x
      Role: arn:aws:iam::803928384365:role/LambdaSampleRole
      Timeout: 10
