Resources:
  EBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-northeast-1a
      SnapshotId: snap-0a9bae50b60eec875

# aws cloudformation create-stack --stack-name snap --template-body file://snapshot.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback
Outputs:
  Volume:
    Value: !Ref EBSVolume
    Description: New EBS volume
